version: '3.1'

services:
  productservice:
    build: .
    ports: 
      - "9000:80"
    depends_on:
      - sql-server 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
    

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tanaton100
    volumes:
      - /var/opt/mssql
   
